services:
  mysql:
    image: mariadb:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./php/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html:cached
      - ./php/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      VIRTUAL_HOST: bfasystem.localhost
